name: UnitTests

on: [push, pull_request]

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt --upgrade pip

    - name: Run tests
      run: bash -x scripts/run_tests.sh

    - name: Archive reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: reports
